### ISSUE TITLE
（提案）フェンスノードについて

### ISSUE THREAD

**Issue by Rui914** [duroom-zacc/micrize-modpack#1]
フェンスを設置した際に黒いノードが一瞬表示されると思います。
これらは私が考えた対処法の一覧です。参考になればと思います。
（プログラム初心者なので、あまり当てにはならないと思います）

●paramtype = "light"を追加
黒くなくなりますが、一瞬表示されるのは変わりません

●Node_boxを０番フェンスと同じにする
置いた時に目立ちませんが、インベントリアイコンが犠牲になります

●Node_boxを０番フェンスと同じにし、アイコンを画像にする
デザイン的には最も良い対処法ですが、画像作成の手間が...
defaultのフェンス枠画像を使用するという手もありますが、Minecraftっぽくはないです

ちなみに、ノードのコールバックで変化させてみましたが、どれも一瞬表示されてしまい、効果ありませんでした。

勝手にIssueしてすみません。Wikiの掲示板にMod作成スレを立てるべきでしょうか？

**Comment by duroom-zacc** [comment]
僕も気になってはいるのですが、良いアイデアが…。
多分３番めの方法が一番いい方法だと思います。が、ちょっと面倒臭いですね。
あと、テクスチャを変更した際にそれがインベントリイメージに反映されないのも嬉しくないです…。
もしかしたらもう少しいい方法があるかもしれないので、今は保留しときますね(^_^;)

いえいえ、そこまでしていただなくても…(^_^;)
